### ISSUE TITLE
Tangible LineItem parameter should be optional.

### ISSUE THREAD

**Issue by vercotux** [collizo4sky/omnipay-2checkout#1]
According 2checkout [documentation](https://www.2checkout.com/documentation/payment-api/create-sale) a 'tangible' LineItem attribute is optional. Currently it is [mandatory](https://github.com/collizo4sky/omnipay-2checkout/blob/50b50972f610bf54e6ed95ef4b0d3fbd3198c4f7/src/Message/PurchaseRequest.php#L49). Just a minor inconvenience tho.

Great work on the implementation btw. Will rely on it heavily!

**Comment by collizo4sky** [comment]
Just seeing this issue. If you can, pull request is welcomed. I will address this as soon as i have the time.

**Comment by collizo4sky** [comment]
Fixed #3
