### ISSUE TITLE
Support for refund

### ISSUE THREAD

**Issue by mpoiriert** [collizo4sky/omnipay-2checkout#10]
It's seem from 2 checkout api that it does support refund

https://www.2checkout.com/documentation/api/sales/refund-invoice

Is there a reason it's not integrated in the gateway ?

If there is no reason why not I will probably do it where I work and submit a pull request.

From what I see there is no integration test ? So for unit test I just validate the input/outpu without really calling the 2checkout api ?

**Comment by collizo4sky** [comment]
Yea, no integration test. But be sure to confirm it is working at your end before submitting a PR.

Would love to see this added too.

**Comment by collizo4sky** [comment]
Added. see ef5536910
