### ISSUE TITLE
Support for Api

### ISSUE THREAD

**Issue by developernaren** [collizo4sky/omnipay-2checkout#11]
There is [this documentation](https://www.2checkout.com/documentation/payment-api) for api payment in 2checkout but this seems to be missing in this repo. I cannot seem to create token using this repo, that I can later charge the card with, It either supports the one where I have get redirected to the 2 checkout's site itself or I have to have a token with me before I start transaction.

can you add this support or am I missing something?

**Comment by developernaren** [comment]
This seems to be issue with how 2checkout handles api. This I do not think is a issue now.

**Comment by collizo4sky** [comment]
You need to use 2checkout JS library to generate the token. With the token, you can use this Omnipay driver to make a transaction. See the readme.
