### ISSUE TITLE
Call to undefined method Omnipay\Common\CreditCard::getPhoneExtension()

### ISSUE THREAD

**Issue by developernaren** [collizo4sky/omnipay-2checkout#12]
I get this error which seem like the error with CreditCard, I think this call should be removed

**Comment by collizo4sky** [comment]
What version of Omnipay common is installed in your project? It seems an older one. Upgrade to the latest version.

**Comment by developernaren** [comment]
"omnipay/omnipay": "^2.3",
this is the omnipay I am using.

**Comment by collizo4sky** [comment]
Upgrade to at least 2.4.1

**Comment by developernaren** [comment]
I just updated to 2.3.4 but still not such method

* The full list of card attributes that may be set via the parameter to
 * *new* is as follows:
 *
 * * title
 * * firstName
 * * lastName
 * * name
 * * company
 * * address1
 * * address2
 * * city
 * * postcode
 * * state
 * * country
 * * phone
 * * fax
 * * number
 * * expiryMonth
 * * expiryYear
 * * startMonth
 * * startYear
 * * cvv
 * * issueNumber
 * * billingTitle
 * * billingName
 * * billingFirstName
 * * billingLastName
 * * billingCompany
 * * billingAddress1
 * * billingAddress2
 * * billingCity
 * * billingPostcode
 * * billingState
 * * billingCountry
 * * billingPhone
 * * billingFax
 * * shippingTitle
 * * shippingName
 * * shippingFirstName
 * * shippingLastName
 * * shippingCompany
 * * shippingAddress1
 * * shippingAddress2
 * * shippingCity
 * * shippingPostcode
 * * shippingState
 * * shippingCountry
 * * shippingPhone
 * * shippingFax
 * * email
 * * birthday
 * * gender
 *

This is the list of everything a credit card can have according to the `CreditCard` class.

**Comment by developernaren** [comment]
composer says there is not 2.4

**Comment by collizo4sky** [comment]
There is. See https://github.com/thephpleague/omnipay-common/releases

**Comment by developernaren** [comment]
it is because I am using `omnipay` and it is pulling in the 2.3 of the `omnipay/common`. there was an issue with laravel integrating omnipay in 5.2 because of some http symphony package.

**Comment by developernaren** [comment]
![omnipay](https://cloud.githubusercontent.com/assets/3628468/17091038/36440bbc-5256-11e6-94ea-71a1a3630e28.png)
I get this when I try to install omnipay common, I am confused now as to how to do this. This may be the issue with the main omnipay repo, but do you have any idea as to how to solve this, or can you add like a `method_exists` in your file to fix this. My realease is being pushed back because of this issue.

**Comment by collizo4sky** [comment]
You just have to upgrade to fix your problem. Am afraid, this is how far i
can comment on this.

Regards.

**Comment by collizo4sky** [comment]
There is no package called omnipay/omnipay. Where are you pulling that from?

**Comment by developernaren** [comment]
There is one package omnipay/omnipay but this seems like an old package, that is need to be used with the current version of laravel. I will either have to abandon this package and start writing everything from scratch. this is a never ending loop of unstatisfiable dependencies that is just pushing my realeas, you gotta help me out man. if you fix that with a method exists, that would be a big big help.

This is the issue I get when I try to install omnipay/common

![omnipay1](https://cloud.githubusercontent.com/assets/3628468/17091157/9f7eca4e-5257-11e6-8f70-2c3805c64b9f.png)

**Comment by collizo4sky** [comment]
Your best option now is to fork this repo, remove the phoeextension method
and add a "repository" json object to your composer.json file so it fetches
from your repo instead of mine.

"repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/yourusername/your-forked-slug/"
  }
],

**Comment by developernaren** [comment]
Can i make a pull request with the `method_exists` check in you repo? would you accept that PR?

**Comment by collizo4sky** [comment]
No. I won't.  Doesn't make sense.

**Comment by developernaren** [comment]
you should at least put a notice there warning people to not use this repo with laravel and save everyones' ( who are using this with laravel ) time. This was supposed to save time but I will have to rework my code because you refused to add a simple if statement to make it backward compatible.

**Comment by collizo4sky** [comment]
It does work with Laravel and any PHP framework. You need to resolve your
project dependencies.

**Comment by developernaren** [comment]
I just clearly showed you that it doesn't work with Laravel 5.2 with
screenshots.
