### ISSUE TITLE
Why did you add set/get Cart method? I see in abstract request exists already setItems.

### ISSUE THREAD

**Issue by parfumix** [collizo4sky/omnipay-2checkout#14]
I think will be fine to use set/get Items to keep abstraction. For example in my case i have a general controller which use 2 different payment gateways.
1. 2Checkout - for setup products i have to use setCart()
2. MultiSafepay - for setup products i have to use setItems()

and in controller appear hardcoding like this if( method_exists($gateway, 'setCart') ) else( method_exists($gateway, 'setItems') ) 

Thank you.

**Comment by collizo4sky** [comment]
Because get/set items do not conform to how 2Checkout will want cart items to be presented (in json)
