### ISSUE TITLE
Notice  if ($this->data['sandbox']) { ..

### ISSUE THREAD

**Issue by parfumix** [collizo4sky/omnipay-2checkout#15]
I always on dev working with error_reporting = -1 display_errors = 1 which mean show all errors / warnings etc..

If i do : $gateway = OmniPay::create('TwoCheckoutPlus')->setTestMode(false);

i got : Notice: Undefined index: sandbox in /vagrant/../vendor/collizo4sky/omnipay-2checkout/src/Message/PurchaseResponse.php on line 23

Thank you.

**Comment by collizo4sky** [comment]
see #4
