### ISSUE TITLE
Can not set returnUrl

### ISSUE THREAD

**Issue by hainguyenhd** [collizo4sky/omnipay-2checkout#16]
Hi mr,
I can not set the returnUrl when use 'TwoCheckoutPlus'. It says 'Fatal error: Call to undefined method Omnipay\TwoCheckoutPlus\Gateway::setReturnUrl()'.

Thank you,
Hai Nguyen

**Comment by collizo4sky** [comment]
Add `'returnUrl' => $return-url-var` to the array parameter supplied to `$gateway->purchase()` like so

```
$response = $gateway->purchase(
                    array(
                        'card' => $formData,
                        'transactionId' => $order->get_order_number(),
                        'currency' => get_currency(),
                        'returnUrl' => $returnUrl,
                    )
            )->send();
```
