### ISSUE TITLE
ERROR CODE:PE101 in test mode

### ISSUE THREAD

**Issue by gplcart** [collizo4sky/omnipay-2checkout#17]
Hello
Dont know why by sending test payments to https://sandbox.2checkout.com/checkout/purchase causes ERROR CODE:PE101.

However sending the same test payments to live endpoint https://2checkout.com/checkout/purchase (demo mode is set as parameter or in account settings) works just fine. There's just "This is a demo sale. Your card will not be charged." notation appears on the landing page

Maybe remove https://sandbox.2checkout.com/checkout/purchase?

**Comment by collizo4sky** [comment]
Please see #4
