### ISSUE TITLE
Possible issue with test mode

### ISSUE THREAD

**Issue by joomdonation** [collizo4sky/omnipay-2checkout#4]
Hi

Thanks for accepting my PR. There is a possible issue with this block of code:

https://github.com/collizo4sky/omnipay-2checkout/blob/master/src/Message/CompletePurchaseRequest.php#L33-L36

From my test, that block of code is not necessary at all. If we have that block of code, test mode won't work with 2Checkout, I had to remove that block of code in my product

Maybe you should check it

**Comment by collizo4sky** [comment]
Hi, i guess i need to explain how the test and demo mode is set up.

When `demoMode` is set to true, the payment apparently will be a test payment but send to 2checkout live API endpoint.

And when `testMode` is set to true, the sandbox API endpoint is used instead.

In demoMode, all order ID or number are set to `1` when 2co generate the md5 harsh of the transaction. Thus the need for that code block to be able to successfully verify the harsh.

See https://www.2checkout.com/documentation/checkout/return

**Comment by joomdonation** [comment]
Ah, OK. Thanks for the explanation. I don't have a Live 2Checkout account for testing, only test it by sandbox account and didn't understand the meaning of the parameter.
