### ISSUE TITLE
Complete purchase amount validation

### ISSUE THREAD

**Issue by m1r0** [collizo4sky/omnipay-2checkout#7]
The CompletePurchase md5 key is not validating the purchase amount, only the account number and the secret word.

Possible fix: https://github.com/thephpleague/omnipay-2checkout/blob/master/src/Message/CompletePurchaseRequest.php#L21

**Comment by collizo4sky** [comment]
Apparently your statement isn't true. See https://github.com/collizo4sky/omnipay-2checkout/blob/master/src/Message/CompletePurchaseRequest.php#L38
