### ISSUE TITLE
Fatal error: Call to undefined method Omnipay\TwoCheckoutPlus\TokenGateway::setApiKey()

### ISSUE THREAD

**Issue by volomike** [collizo4sky/omnipay-2checkout#8]
I'm hoping to use the token method of purchase.

I used composer to install this, and it created this path:

  omnipay\vendor\collizo4sky\omnipay-2checkout

note also that I have this path:

  omnipay\vendor\omnipay

...containing "common" and "stripe" folders

I have Stripe working from its own separate cart folder on my project just fine. With that, I merely did:

```
use Omnipay\Omnipay;
$oGateway = Omnipay::create('Stripe');
$oGateway->setApiKey($config->STRIPE_SECRET_KEY);

```

But for my 2Checkout cart folder in my project, I tried to run it like so:

```
use Omnipay\Omnipay;
$oGateway = Omnipay::create('TwoCheckoutPlus_Token');
$oGateway->setApiKey($config->TWOCHECKOUT_SECRET_KEY);

```

...but it's crashing with the fatal error that it can't find the API path. The error is:

Fatal error: Call to undefined method Omnipay\TwoCheckoutPlus\TokenGateway::setApiKey()

**Comment by collizo4sky** [comment]
2co doesn't has a secretKey but privateKey.  For a list of setter methods, see https://github.com/collizo4sky/omnipay-2checkout/blob/master/src/Message/AbstractRequest.php

**Comment by volomike** [comment]
Please reopen. That's just the variable name. It means nothing in your API. That variable is from my own config.php. Yes -- I call it "secret key", but it's really the "private key". My problem appears to be in trying to get the "use" statements worked out with the folder path in my omnipay\vendor folder, and knowing what to put in the Omnipay::create() class method.

**Comment by collizo4sky** [comment]
Solution is, use `setPrivateKey` method instead of `setApiKey` that you are using.

**Comment by volomike** [comment]
Ah, that got me further. It's still broke, though. I'm now doing:

```
use Omnipay\Omnipay;
$sMerchantTransID = md5('MY_TRANS' . $sDate);
$oGateway = Omnipay::create('TwoCheckoutPlus_Token');
$oGateway->setPrivateKey($config->TWOCHECKOUT_SECRET_KEY); // yes, the private key
$oGateway->setAccountNumber($config->TWOCHECKOUT_SELLERID);
$oResponse = $oGateway->purchase(array(
	'amount' => $sPrice,
	'currency' => 'USD',
	'token' => $sToken,
	'description' => $sDesc,
	'transactionId' => $sMerchantTransID
))->send();

```

The order goes through the API, but then I get this error:

Unauthorized

I then added a line before the purchase:

`$oGateway->setTestMode(true);
`

And now I get:

Authorization Failed

**Comment by collizo4sky** [comment]
Are you using a sandbox or production account for testing? Please see #4

**Comment by volomike** [comment]
I appreciate your help. I have a deadline on this by tomorrow and thought this would be easier than this since Stripe was easy and 2checkout didn't look that much harder than that.

I'm using the sandbox. I read #4 and yes, am using setTestMode(true). I also thought, hmmm..., maybe the transactionId needs to be numeric, so I did rand(11111111,99999999) for it for now to see if I can just get this to work. I get Authorization Failed.

In my tests, the token seems to work, but the authorization is failing with the key and the token not matching:

screen capture from the sandbox:
http://screencast.com/t/IQKk6N0o

Code used:

```
use Omnipay\Omnipay;
$sMerchantTransID = rand(11111111,99999999);
$oGateway = Omnipay::create('TwoCheckoutPlus_Token');
$oGateway->setPrivateKey($config->TWOCHECKOUT_PRIVATE_KEY);
$oGateway->setAccountNumber($config->TWOCHECKOUT_SELLERID);
$oGateway->setTestMode(true);
$oResponse = $oGateway->purchase(array(
	'amount' => $sPrice,
	'currency' => 'USD',
	'token' => $sToken,
	'transactionId' => $sMerchantTransID
))->send();

```

**Comment by volomike** [comment]
I dumped out the $data var from the TokenPurchaseRequest.php to a text file and it reads like the following. (Note, those aren't my sellerID, privateKey, and token variables below. They are examples for pasting here. I used my real ones in the sandbox, and from the sandbox settings, not the production settings.)

```
array (
  'sellerId' => '901414261',
  'privateKey' => 'EAEC8615-4C48-4D98-B7E5-4B6D8865E1BA',
  'merchantOrderId' => 65639323,
  'token' => 'FDI1ZTM3N2UtY2VkZS00NTM1LWE5MTctYzI4MjA5YWI4Yjhm',
  'currency' => 'USD',
  'total' => '519.00',
)
```

It then generated this error response:

```
HTTP/1.1 400 Bad Request
Server: Apache-Coyote/1.1
Cache-Control: no-cache, no-store, must-revalidate
Date: Fri, 22 Apr 2016 03:30:37 GMT
Expires: 0
Pragma: no-cache
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked

{"validationErrors":null,"response":null,"exception":{"errorMsg":"Authorization Failed","httpStatus":"400","exception":false,"errorCode":"600"}}
```

**Comment by volomike** [comment]
Latest: I tried the 2Checkout-approved version of the API for PHP. I get the same exact issue -- Authorization Failed. When I check on what that error meant, the documentation tells me that the credit card failed. I was using the one that the sandbox docs said to use, and used a CVV of 123 and an expiration of 12/18. I then thought that perhaps it wanted the year in 4 digits, so I tried that and it still failed.

My gut feeling is that the problem might lie in the fact that my regular account is not yet approved? I mean, I would have assumed that the sandbox would still work even if the regular account is not yet approved, right? Perhaps not?

**Comment by collizo4sky** [comment]
I once had similar issue. This occur if you created the credit card token using the production api endpoint rather than that of sandbox.

Ensure you generated the credit card token via the sandbox api and also u are processing the token server side with sandbox mode.

**Comment by volomike** [comment]
Doesn't seem to be the answer for me just yet. Good guess, though. I wish it we were getting closer. Looking at a sample of my client-side code when I did a "View Source", it looked like this and was called right after my form validated properly in jQuery. The sellerID and publishableKey are changed below for privacy reasons of course, but I did pull them from the sandbox. (Yep, and I tried regenerating the API keys again in the sandbox and retesting -- still get a credit card failure.)

```
var args = {
	sellerId: "901314365",
	publishableKey: "0BBA13D9-BDC0-4F3E-8973-57255F3E293B",
	ccNo: $("#ccnumber").val(),
	cvv: $("#cccode").val(),
	expMonth: $("#ccexpmonth").val(),
	expYear: '20' + $("#ccexpyear").val()
};
TCO.loadPubKey("sandbox",function(){
	TCO.requestToken(successCallback,errorCallback,args);
});
```

Then, server side, as long as I set the test mode to true, that's the sandbox, right?

`$oGateway->setTestMode(true);
`

My hunch is that something is up with my sandbox account -- perhaps they don't let your sandbox work 100% until you've been approved on your live account?

**Comment by collizo4sky** [comment]
Did you also made setDemoMode true ?

See issue #4

**Comment by volomike** [comment]
When I try that, I get this error:

Call to undefined method Omnipay\TwoCheckoutPlus\TokenGateway::setDemoMode()

**Comment by volomike** [comment]
That fixed it. Yay! I couldn't do it from the TCO API, but could do it from the settings in the sandbox.

Screen capture:

http://screencast.com/t/PkkVwWJ7ZjH

**Comment by collizo4sky** [comment]
Great.

I can now concentrate on my exam.

Been answering u while waiting for the commencement of my paper 😎

**Comment by volomike** [comment]
Carry on, and much appreciated. BTW, I don't know if Github told you, but I made an adjustment to TokenGateway.php to accept that getDemoMode() parameter because it wasn't.

**Comment by collizo4sky** [comment]
Can't find anything. Did you submit a pull request.

**Comment by volomike** [comment]
Ah, reject that. My code change probably wouldn't work, anyway. Here's what I found out about the Demo Mode in 2Checkout. If Demo Mode is set to "Y" (as a parameter -- it doesn't like a 1 or 0 or true or false, but wants to see "Y" or "N" and by default is "N" if left out), then transactions go through but never as a sale that you can actually refund. Also, the test cards they provide work without issue, even without billing address info. However, when Demo Mode is set to "N", then transactions go through as a sale that you can actually refund, but only work if there's a billing address -- they won't work without it. That's a showstopper for some people -- I mean, luckily my cart requires a billing address, but to others, they may have to use Stripe, which doesn't require a billing address in order for a sale to go through.

So, again, the recommended setting in the sandbox is to set the Demo mode manually to Off. That's the only way you'll get something to appear in the Sales tab that you can actually refund, and that's the point, really, isn't it? However, once that setting is set to Off, you'll need to pass a billing address or the order will come back as "Authorization Failed" and you'll never see an item in the Sales tab.

**Comment by collizo4sky** [comment]
Glad you have it figured out already.
